### ISSUE TITLE
TypeError: new(): invalid data type 'str'

### ISSUE THREAD

**Issue by ZJX-CV** [bismex/MetaBIN#11]
def fast_batch_collator(batched_inputs):
    """
    A simple batch collator for most common reid tasks
    """
    elem = batched_inputs[0]
    if isinstance(elem, torch.Tensor):
        out = torch.zeros((len(batched_inputs), *elem.size()), dtype=elem.dtype)
        for i, tensor in enumerate(batched_inputs):
            out[i] += tensor
        return out

    elif isinstance(elem, container_abcs.Mapping):
        return {key: fast_batch_collator([d[key] for d in batched_inputs]) for key in elem}

    elif isinstance(elem, float):
        return torch.tensor(batched_inputs, dtype=torch.float64)
    elif isinstance(elem, int_classes):
        return torch.tensor(batched_inputs)  # bug!!!
    elif isinstance(elem, string_classes):
        return batched_inputs

**Comment by bismex** [comment]
Hello, 

What command did you run the code with? Have you changed anything?

**Comment by ZJX-CV** [comment]
Hello, ^_^
i run this project with  the following command:
python ./tools/train_net.py --config-file ./configs/Sample/DG-resnet.yml OUTPUT_DIR "/data/zjx/" MODEL.DEVICE "cuda:0"

i changeed part of DG_cuhk_sysu.py, because the original code can not work in CUHK_SYSU dataset( my dataset only have a "cropped_image" folder，and images in this folder named like "p3215_s4118_2.jpg"). this new code is find in fastreid project.

![image](https://user-images.githubusercontent.com/85015879/144970716-49f1171e-9918-481e-9a08-7885de3414b1.png)


**After printing the bug info like this:**

![image](https://user-images.githubusercontent.com/85015879/144970610-20283613-c895-48d6-93c5-9f5ee62f46d0.png)


**i find some element in this list are not int......*—*** 

output like this:
67 CUHK-SYSU_8    
72 CUHK-SYSU_1
73 CUHK-SYSU_1
74 CUHK-SYSU_1
75 CUHK-SYSU_1
76 CUHK-SYSU_1
77 CUHK-SYSU_1
78 CUHK-SYSU_1
79 CUHK-SYSU_1

**Comment by ZJX-CV** [comment]
i am wonder that what are the input of fast_batch_collator(), why there are int and str in a list? please wuwu...

> Hello,
> 
> What command did you run the code with? Have you changed anything?

^_^ i am wonder that what are the input of fast_batch_collator(), why there are int and str in a list? this problem confuse me a lot @bismex

**Comment by bismex** [comment]
The error seems to occur because the format of fetching the 'pid' and 'camid' from the dataset file is different. Please refer to the 'pid' and 'camid' of the DG_cuhk_sysu.py code so that they can be loaded in the same format. The code of fastreid you used seems to get the 'camid' in the form of a string. On the other hand, in my code, 'camid' is called in int form.

Please check the below file.
(https://github.com/bismex/MetaBIN/blob/master/fastreid/data/datasets/DG_cuhk_sysu.py) 

E.g
pid = 'datasetname_0001' # str
camid = 1 # int

**Comment by ZJX-CV** [comment]
> The error seems to occur because the format of fetching the 'pid' and 'camid' from the dataset file is different. Please refer to the 'pid' and 'camid' of the DG_cuhk_sysu.py code so that they can be loaded in the same format. The code of fastreid you used seems to get the 'camid' in the form of a string. On the other hand, in my code, 'camid' is called in int form.
> 
> Please check the below file. (https://github.com/bismex/MetaBIN/blob/master/fastreid/data/datasets/DG_cuhk_sysu.py)
> 
> E.g pid = 'datasetname_0001' # str camid = 1 # int

Thank you very much! The project is running now!  wow the large-scale DG  benckmark seems to take a lot of time to train the model. code is already running for five minutes, but nothing has been printed.
![image](https://user-images.githubusercontent.com/85015879/144983511-0b1db228-1f80-48eb-8d1a-ceac945cfdf7.png)

**Comment by bismex** [comment]
Good luck with your research!
