### ISSUE TITLE
CUHK-SYSU dataset struct

### ISSUE THREAD

**Issue by huangpan2507** [bismex/MetaBIN#14]
your cuhk-sysu dataset show like below:
CUHK-SYSU/
├── annotation/
├── Image/
├── cropped_image/
├── make_cropped_image.m (my matlab code)

but the structure of dataset i download just like this:
cuhksysu/
├── cropped_images/

or this:
cuhksysu/
├──images/
├──labels_with_ids/

**Comment by huangpan2507** [comment]
I have find the suite dataset that have the same structure

**Comment by mumumu77** [comment]
Please tell me the suite dataset...

**Comment by Zzhc3321** [comment]
"but the structure of dataset i download just like this:
cuhksysu/
├── cropped_ images/"

Can you tell me how to download the above dataset? Recently, I have been running code, but the dataset is always inconsistent with the one used in the source code, and the dataset is exactly the one you mentioned above.

**Comment by ds-giao** [comment]
@huangpan2507 Hello friends，could you tell me how to find the suite cuhk-sysu as you say? Thank you!
