### ISSUE TITLE
what is the mean of flag_pos and neg_flag in the  def triplet_loss(embedding, targets, margin, norm_feat, hard_mining, dist_type, loss_type, domain_labels = None, pos_flag = [1,0,0], neg_flag = [0,0,1])?

### ISSUE THREAD

**Issue by xal2019** [bismex/MetaBIN#2]
In 
def triplet_loss(embedding, targets, margin, norm_feat, hard_mining, dist_type, loss_type, domain_labels = None, pos_flag = [1,0,0], neg_flag = [0,0,1]), what is mean of pos_flag  and pos_flag ? And why set them as [1, 0, 0] and [0,1,1]?

**Comment by bismex** [comment]
Hello. Thank you for your interest in my paper.

As you can see in my paper, we designed two types of triplet-like losses (in Eq 3 & 7). The two flags (pos_flag and neg_flag) depend on whether you want to pull or push the samples towards the anchor. The pos flag indicates which sample to pull and the neg flag is the opposite.

There are three elements in the flags, which are positive samples, intra-domain negative samples, inter-domain negative samples, respectively. You just ignore the default values (pos = [1,0,0], neg = [0,0,1].) You can check the cases of flags in "MetaBIN/configs/Base-DG.yml".

In the triplet loss in Eq. 3, we set the pos vector as [1,0,0] and the neg vector as [0,1,1], which aims to pull positive samples and push negative samples (including intra-domain, inter-domain neg samples). 

In the inter-domain shuffle loss in Eq. 7, we set the pos vector as [0,0,1] and the neg vector as [0,1,0], which aims to pull inter-domain neg samples and push intra-domain neg samples. The purpose of this is to shuffle different domain samples. 

If you have any questions, please let me know.
