### ISSUE TITLE
The parameter updation

### ISSUE THREAD

**Issue by yjh576** [bismex/MetaBIN#4]
As said in this paper, you separate an episode that updates the balancing parameters from another episode
that updates the rest of the parameters, and then perform both episodes alternately at each training iteration.
However, I did not find the corresponding code for this part. I found that all the parameters are updated at the same time.
Please help answer some of my confusion. Thank you.

**Comment by bismex** [comment]
Thanks for your interest.
Please check Section 9 (code structure) on the readme page.

As you see this part, we divided our training schedule into two parts as below.
- run_step_meta_learning1(): update base model
- run_step_meta_learning2(): update balancing parameters (meta-learning)

**Comment by yjh576** [comment]
Yes, run_step_meta_learning1() and run_step_meta_learning2() are with the same self.basic_forward(). I don't know how this code controls balancing parameters updates. What I understand is that they share a model. Therefore, all parameters are updated at the same time.

**Comment by bismex** [comment]
You can confirm the two different optimizers in the [code](https://github.com/bismex/MetaBIN/blob/c849b13750c480fed90ad9e8339209f745c1c65b/fastreid/engine/defaults.py#L188).
It can be seen that one optimizer includes a parameter called 'gate' (balancing parameters) and one does not. (check [this](https://github.com/bismex/MetaBIN/blob/master/fastreid/solver/build.py#L32))

In the base model update [code](https://github.com/bismex/MetaBIN/blob/master/fastreid/engine/train_loop.py#L443), we use only 'optimizer_main' for backward. 
In the meta-learning [code](https://github.com/bismex/MetaBIN/blob/master/fastreid/engine/train_loop.py#L485), we use only 'optimizer_norm' for backward.

**Comment by yjh576** [comment]
Thank you for your reply. I understand it. I will look at this part again.

**Comment by bismex** [comment]
Thanks, I will close this issue.
