### ISSUE TITLE
Performance difference between trained model and reported result

### ISSUE THREAD

**Issue by EquiKuma** [bismex/MetaBIN#5]
Hi,
Thanks for sharing the awesome code. I followed the training instructions in README.md, and run the following code:
`python3 ./tools/train_net.py --config-file ./configs/Sample/DG-mobilenet.yml MODEL.DEVICE "cuda:0"`

The program runs well, and after training, I got the following results:
 `Evaluation results in csv format:
| Datasets                  | Rank-1   | Rank-5   | Rank-10   | mAP    | mINP   | TPR@FPR=0.0001   | TPR@FPR=0.001   | TPR@FPR=0.01   |
|:--------------------------|:---------|:---------|:----------|:-------|:-------|:-----------------|:----------------|:---------------|
| ALL_GRID_average          | 40.80%   | 63.20%   | 74.40%    | 51.29% | 51.29% | 0.00%            | 0.00%           | 11.34%         |
| ALL_GRID_std              | 0.00%    | 0.00%    | 0.00%     | 0.00%  | 0.00%  | 0.00%            | 0.00%           | 0.00%          |
| ALL_VIPER_only_10_average | 61.08%   | 78.80%   | 86.08%    | 69.36% | 69.36% | 0.00%            | 0.00%           | 38.14%         |
| ALL_VIPER_only_10_std     | 0.00%    | 0.00%    | 0.00%     | 0.00%  | 0.00%  | 0.00%            | 0.00%           | 0.00%          |
| ALL_PRID_average          | 77.00%   | 90.00%   | 94.00%    | 83.01% | 83.01% | 0.00%            | 0.00%           | 81.95%         |
| ALL_PRID_std              | 0.00%    | 0.00%    | 0.00%     | 0.00%  | 0.00%  | 0.00%            | 0.00%           | 0.00%          |
| ALL_iLIDS_average         | 81.67%   | 96.67%   | 98.33%    | 88.32% | 88.32% | 0.00%            | 0.00%           | 61.50%         |
| ALL_iLIDS_std             | 0.00%    | 0.00%    | 0.00%     | 0.00%  | 0.00%  | 0.00%            | 0.00%           | 0.00%          |
| ** all_average **         | 65.14%   | 82.17%   | 88.20%    | 72.99% | 72.99% | 0.00%            | 0.00%           | 48.23%         |
[08/16 17:30:24 fastreid.utils.events]: eta: 0:00:01  iter: 184899  total_loss: 3.406  1)loss_cls: 1.441  1)loss_triplet: 0.001  2)loss_stc: 0.920  2)loss_triplet_add: 1.049  2)loss_triplet_mtrain: 0.000  3)loss_triplet_mtest: 0.000  time: 1.6764  data_time: 0.0224  lr: N/A  max_mem: 6326M`

The result seems quite different from the paper, e.g., Rank1 on GRID is 40.8, while in the paper it is 48.4, for all other datasets the results are 2~3% better. Can you share your config for training "model_0099999.pth", so we can reproduce similar results 
in paper？ Thanks!

**Comment by bismex** [comment]
As far as I remember, the config is the same. Although the seed is fixed, the reproduction result is different every time. Unfortunately, the scale of the target dataset is relatively small, so the results are unstable. This issue has not been resolved yet.

If you want to get similar results, we recommend that you try again a few times.

**Comment by EquiKuma** [comment]
OK, I will try a few times more. Thanks for the response!

**Comment by bismex** [comment]
Thanks!
