### ISSUE TITLE
Questions abount model selection methods

### ISSUE THREAD

**Issue by yfzhang114** [bismex/MetaBIN#6]
I wanna where are the final model comes from?
1. It is chosen by the performance of the test datasets.
2. It is just the last checkpoint of the experiment.

**Comment by bismex** [comment]
Thanks for your interests in my paper. I think I chose the best result.
However, I remember that the best result did not differ that much from the last checkpoint result.

**Comment by yfzhang114** [comment]
> Thanks for your interests in my paper. I think I chose the best result.
> However, I remember that the best result did not differ that much from the last checkpoint result.

Thanks for your reply!

**Comment by yfzhang114** [comment]
Solved
