### ISSUE TITLE
About the setting of single-source DG training

### ISSUE THREAD

**Issue by aloneCR** [bismex/MetaBIN#7]
Hello, I am trying to reproduce the work of this paper. But I want to try to place a single source domain test. I have downloaded the data set Market1501 and DukeMTMC-REID, and set the corresponding data set according to your document.
But your document does not mention how to set up a single source domain and perform training. I did some attempts by myself but an error occurred when the program was running.

After setting the DATASETS in file ./configs/Sample/DG-mobilenet.yml, I try to train by "python3 ./tools/train_net.py --config-file ./configs/Sample/DG-mobilenet.yml MODEL.DEVICE "cuda:4". 
![image](https://user-images.githubusercontent.com/30072589/134627128-96e803a6-0fe4-44c2-b2f5-0b848a9c103a.png)

But I got an error as below: 

```python
Traceback (most recent call last):
  File "./tools/train_net.py", line 142, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)b
  File "./fastreid/engine/defaults.py", line 539, in train
    super().train(self.start_iter, self.max_iter)y
    self.run_step_meta_learning2() # update balancing parameters (meta-learning)
  File "./fastreid/engine/train_loop.py", line 638, in run_step_meta_learning2
    opt['domains'] = data_mtest['others']['domains']
TypeError: 'NoneType' object is not subscriptable
```
I am very distressed, can you tell me the settings for single-source domain training? Many thanks!!

**Comment by bismex** [comment]
Hello, sorry for the late reply. 
We also provide single-source domain experiments.
Please check 'D-resnet.yml' and 'M-resnet.yml' (https://github.com/bismex/MetaBIN/tree/master/configs/Sample).
Thanks!
